
title: "My Stylish Blog"
description: "Jekyll + GitHub Pages で作るシンプルで美しいブログ"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/yukanamori" }
